version: '3.7'

x-defaults: &defaults
  restart: always
  init: true

  env_file:
    - .env

  environment: &environment
    DOCKER: true
    NODE_ENV: production
    REDIS_HOST: redis
    REDIS_PORT: 6379
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432

  logging:
    driver: 'json-file'
    options:
      max-size: '5m'
      max-file: '10'
      tag: '{{.Name}}'

services:
  postgres:
    <<: *defaults
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - ${DOCKER_NETWORK}

  redis:
    <<: *defaults
    image: redis:7.2-alpine
    volumes:
      - ./data/redis:/data

  api:
    <<: *defaults
    image: ghcr.io/DecouvreBitcoin/sovereign-university-api:${IMAGE_TAG}
    environment:
      <<: *environment
      HOST: 0.0.0.0
      PORT: 3000
    expose:
      - 3000
    volumes:
      - ./data/cdn:$CDN_PATH
    labels:
      - traefik.enable=true
      - traefik.http.routers.university-api.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.university-api.entrypoints=https,http
      - traefik.http.routers.university-api.tls=true
      - traefik.http.routers.university-api.tls.certresolver=security
      - traefik.http.services.university-api.loadbalancer.server.port=3000
      - traefik.http.routers.university-api.service=university-api
    depends_on:
      - postgres
    networks:
      - ${DOCKER_NETWORK}

  cdn:
    <<: *defaults
    image: nginx:latest
    volumes:
      - ./config/cdn/nginx.conf:/etc/nginx/nginx.conf
      - ./data/cdn:/var/www/cdn
    labels:
      - traefik.enable=true
      - traefik.http.routers.university-cdn.rule=Host(`cdn.${DOMAIN}`)
      - traefik.http.routers.university-cdn.entrypoints=https,http
      - traefik.http.routers.university-cdn.tls=true
      - traefik.http.routers.university-cdn.tls.certresolver=security
    networks:
      - ${DOCKER_NETWORK}

  web:
    <<: *defaults
    image: ghcr.io/DecouvreBitcoin/sovereign-university-web:${IMAGE_TAG}
    volumes:
      - ./config/web/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.university-web.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.university-web.entrypoints=https,http
      - traefik.http.routers.university-web.tls=true
      - traefik.http.routers.university-web.tls.certresolver=security
      - traefik.http.middlewares.university-web.compress=true
    networks:
      - ${DOCKER_NETWORK}

networks:
  university_testnet:
    external: true
  university_mainnet:
    external: true
